text = "SOCIAL MEDIA PLAYS AN IMPORTANT ROLE IN MODERN LIFE. IT HELPS PEOPLE CONNECT, SHARE INFORMATION, AND COMMUNICATE QUICKLY ACROSS THE WORLD. MANY TEENAGERS USE SOCIAL MEDIA FOR ENTERTAINMENT, EDUCATION, AND KEEPING IN TOUCH WITH FRIENDS. HOWEVER, EXCESSIVE USE OF SOCIAL MEDIA CAN AFFECT STUDIES, HEALTH, AND PERSONAL RELATIONSHIPS. THEREFORE, IT IS IMPORTANT TO USE SOCIAL MEDIA WISELY AND BALANCE ONLINE ACTIVITIES WITH REAL LIFE RESPONSIBILITIES"

print(text.lower())
